### ISSUE TITLE
What are the possible values of timezone?

### ISSUE THREAD

**Issue by Ovilia** [apache/cordova-plugin-globalization#65]
I would like to know the user's timezone information. In my test environment, I got `'GMT+8'`, but I wonder if GMT is the only possible result.
Is it possible to know the offset in hours?

**Comment by janpio** [comment]
Please notice https://github.com/apache/cordova-plugin-globalization#deprecation-notice
So you probably want to use the new standard instead of this plugin.

**Comment by Ovilia** [comment]
Thanks Janpio!
I noticed that you're also an ionic user. So do you know how to use this new standard in ionic? I got a little confused... 😕Or it seems I can also use [moment](https://momentjs.com/timezone/docs/) to get this information? What do you suggest?

**Comment by janpio** [comment]
Honestly no idea - you can probably just use the JS object. Best create a topic at https://forum.ionicframework.com/

**Comment by Ovilia** [comment]
Thanks all the same.
