### ISSUE TITLE
Just the language

### ISSUE THREAD

**Issue by desmeit** [apache/cordova-plugin-globalization#72]
Is it possible to get just the language and not language+region?

I always get the result "de-DE" for example but I just want to get the language "de".

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
