### ISSUE TITLE
Question: When migrating how to get the timezone?

### ISSUE THREAD

**Issue by mkn20** [apache/cordova-plugin-globalization#73]
Hi,

   As this plugin is said to be deprecated, how **exactly** ECMA Internationalization API can then be used to get the device timezone? So, in essence, what is the equivalent (using ECMA Internationalization API)  of navigator.globalization.getDatePattern and using date.timezone from the result? 

Thanks in advance and regards

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
