### ISSUE TITLE
Android app 64 bit requirement

### ISSUE THREAD

**Issue by ASHBAW** [apache/cordova-plugin-globalization#74]
I use the cordova-plugin-globalization plugin in one of my apps.

Google came out with their 64 bit requirement.

[https://9to5google.com/2019/01/15/android-app-64-bit-requirement/](url)

When I searched for .so libraries in my project I saw the following:

```
/plugins/cordova-plugin-globalization/src/blackberry10/native/simulator/libGlobalization.so
/plugins/cordova-plugin-globalization/src/blackberry10/native/device/libGlobalization.so
/node_modules/cordova-plugin-globalization/src/blackberry10/native/simulator/libGlobalization.so
/node_modules/cordova-plugin-globalization/src/blackberry10/native/device/libGlobalization.so
```
I understand that these are blackberry related and not android.  I just wanted to follow up to see if these should be removed to be compliant with Google.

**Comment by agneshoving** [comment]
I was wondering the same thing. Do you have an answer for this @janpio ?

**Comment by janpio** [comment]
That should not be necessary, as only the Android files are copied over to your native Android project and app.

**Comment by jcesarmobile** [comment]
Closing, as janpio said, those are blackberry files, they don't have any effect on the Android apps.
