### ISSUE TITLE
getDatePattern() not returns the updated date time format on resume

### ISSUE THREAD

**Issue by sckumar** [apache/cordova-plugin-globalization#75]
# Bug Report

## Problem
getDatePattern() not returns the updated date time format on resume

getDatePattern() should return the actual date time format of the system
### What does actually happen?
getDatePattern() returns the date time format when I launch the application not the updated system time format
## Information
Launch the application and get the date time format (12hr now). Minimise the app. change the time format to 24hr in settings. onResume try to get the time format should return 24hr but returns 12 hr. Restart the app returns the updated value

### Command or Code
this.globalization.getDatePattern({ formatLength: 'short', selector: 'time' }) on resume

### Environment, Platform, Device
iOS
Ionic

### Version information
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.18.0
    ionic (Ionic CLI) : 3.18.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.2.3
    Cordova Platforms  : android 7.0.0 ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.5

System:

    ios-deploy : 1.9.2 
    ios-sim    : 1.9.0 
    Node       : v8.15.0
    npm        : 6.9.0 
    OS         : macOS
    Xcode      : Xcode 10.2.1 Build version 10E1001 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by janpio** [comment]
Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

**Comment by sckumar** [comment]
@janpio Sorry. I was busy with other things. Here you go..
https://github.com/sckumar/DatePatternIssue

**Comment by sckumar** [comment]
@janpio Any luck ?

**Comment by janpio** [comment]
Not my priority right now, sorry. I work on this stuff when I have free time only (unless someone pays me to work on this). 

But with your repro present, this meets the requirements for a quick verification and identification of the problem, so you did all you can do for now.

**Comment by sckumar** [comment]
Thanks @janpio I have a fix. How to raise PR? Do I need any access to do that ?

**Comment by janpio** [comment]
No, you can just do it all online: https://help.github.com/en/articles/editing-files-in-another-users-repository Let me know if you need any help.

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
