### ISSUE TITLE
Need MSAL Cordova for the Cordova Version 6.5.0

### ISSUE THREAD

**Issue by judefelixantony** [apache/cordova-plugin-globalization#82]
As our Mobile Application is using Cordova Version 6.5.0. Please I need MSAL Cordova which will be combability with this Cordova version 6.5.0

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
