### ISSUE TITLE
Property 'globalization' does not exist on type 'Navigator'

### ISSUE THREAD

**Issue by FrostyMint** [apache/cordova-plugin-globalization#83]
I have install the plugin but it shows my globalization does not exist

**Comment by shenfusheng** [comment]
I got the same error too, is this plugin can still use on cordova-android@10.1.2?

**Comment by pilladooo** [comment]
Hi, 

I update the version of cordova-cli (the latest is 11.0.0) and it worked :)!

**Comment by shenfusheng** [comment]
你好，邮件已收到，谢谢！

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
