### ISSUE TITLE
Support Android 13 per-app language preferences

### ISSUE THREAD

**Issue by ath0mas** [apache/cordova-plugin-globalization#85]
# Feature Request

## Motivation Behind Feature

Watch and support the "Per-app language preferences" introduced in Android 13.

## Feature Description

Android 13 doc: https://developer.android.com/about/versions/13/features/app-languages

**Comment by jcesarmobile** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
